### ISSUE TITLE
Log files not getting generated on windows machines

### ISSUE THREAD

**Issue by Jayesh-asrani-appveen** [appveen/odp-import-export-utility#2]
Log File was not generated during backup or restore. 
Error Logs below.

`  Restore log4js.fileAppender - Writing to file odp_backup_restore_2019-11-16T14:34:43.701Z.log, error happened  { [Error: ENOENT: no such file or directory, open 'D:\Codebase\Appveen\odp-backup-restore-utility\odp_backup_restore_2019-11-16T14:34:43.701Z.log']`

**Comment by jerrymannel** [comment]
This looks like a windows issue. The same issue was reported by someone else too.

**Comment by jerrymannel** [comment]
Fixed. Pull request #5
