### ISSUE TITLE
Need Migration Utility To Work For Different Versions Of ODP

### ISSUE THREAD

**Issue by Mr97Sir** [appveen/odp-import-export-utility#27]
**Is your feature request related to a problem? Please describe.**
Yes. Different environments at the client side are at different versions, so, it isn't feasible to change the version and then migrate the data in the long run.
The issue arises whence we take backup from a different version of ODP and restore it to a different version.

**Describe the solution you'd like**
The config file to have an option to enter the version and the utility stores the data accordingly.

**Describe alternatives you've considered**
The solution currently at work is changing the version of ODP on any one environment and then migrating data after which changing the version again.

**Additional context**

**Comment by jerrymannel** [comment]
ODP migrates the data at each component level and fixes the data at the database level. The recommended approach is to upgrade ODP and that will automatically take care of upgrading the data in the DB.

The current approach for the import export utility is to move configuration from one ODP environment to another, both being at the same version and hot-fix level.

At a client location, please have the same ODP version running in all environments. You cannot have ODP at a higher version say UAT and a lower version in production and vice-versa.

Rejecting the issue and closing it.
