### ISSUE TITLE
When custom partners and flows are selected. It fails to move all the flows present.

### ISSUE THREAD

**Issue by Mr97Sir** [appveen/odp-import-export-utility#4]
Hi,

Tried duplicating from one environment to another using custom partners and flows. The utility only recreated a few of them. Please Check it in the video below.
https://drive.google.com/file/d/1F08guxjfEsLEZVSmimHsIVGumscp0i9G/view?usp=sharing

**Comment by jerrymannel** [comment]
This is a valid issue.
RCA: when you move a flow that uses a data format from one environment to another, the data format id is not getting updated in the flow. The restored flow still points to the old data format id.

**Comment by jerrymannel** [comment]
Fixed
Pull request #5
