### ISSUE TITLE
Unhandled Rejection : Restore 

### ISSUE THREAD

**Issue by Jayesh-asrani-appveen** [appveen/odp-import-export-utility#6]
Got Unhandled Reject : Data.reduce is not a function on migration while restoring the objects onto new instance. Issue came due to groups migration I suppose.

[Migration Logs.zip](https://github.com/appveen/odp-import-export-utility/files/3920601/Migration.Logs.zip)

Attached are the logs and backup files

**Comment by jerrymannel** [comment]
Which version of the tool are you using?

Looks like the user that was used to export the data doesn't have enough permissions. The backup.json file has this error - `"groups": "403 - {\"message\":\"Access denied\"}"`
