### ISSUE TITLE
Unable to deploy flows on separate environment; and kubernetes service for flows starting with apis aren't being created

### ISSUE THREAD

**Issue by Mr97Sir** [appveen/odp-import-export-utility#7]
**Describe the bug**
_Unable to deploy flows on separate environment_
Flows created in one environment and moved to another are not being deployed. (tried this on different environments but still didn't work)

_Kubernetes service for flows starting with apis aren't being created in the same environment._
When copying the flows to a different app in the same environment the api uri to which the flow needs to be hit doesn't have a service being created in the back-end.

**To Reproduce**
_Unable to deploy flows on separate environment_
1. Take backup in one environment.
2. Restore in another environment
3. Check if flows are being deployed
_Kubernetes service for flows starting with apis aren't being created in the same environment._
1. Take backup in one environment.
2. Restore in different app in same environment.
3. Check if service for flow is being created

**Expected behavior**
Flows should be deployed on a different environment
K8s service should be created on the same environment

**Screenshots**
_Unable to deploy flows on separate environment_
https://drive.google.com/open?id=19k4y_uRcW_U_SJUK9YyojfP-Itb6k_Ek

_Kubernetes service for flows starting with apis aren't being created in the same environment._
Expected endpoint is
https://b2b.demo.capiot.com:30016/api
Actual result
https://drive.google.com/open?id=1IW7cIREaS7Zagf-HlLTKTBL0GE4GjnrL
The endpoint seen in the screenshot is the endpoint to the same flow in a different app in the same environment.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Attach files**
https://drive.google.com/open?id=1T_sdneWrxieN-YMvhy6jeECXlFeUv1En

**Comment by jerrymannel** [comment]
While restoring the flow status was being set as Pending. This was preventing the kubernetes service to be created.
